-- 5-17 급여가 2000 이상 3000 이하인 사원 데이터를 조회하시오.
SELECT *
FROM emp
WHERE sal >= 2000 AND sal <= 3000;

-- 5-18
SELECT  * FROM emp WHERE sal BETWEEN 2000 AND 3000;

-- 5-19 sal가 2000에서 3000 사이 값이 아닌 사원 데이터를 조회하시오.
SELECT * FROM emp WHERE sal NOT BETWEEN 2000 AND 3000 ORDER BY sal DESC;

-- 5-20 이름에 대문자 S로 시작하는 사원 데이터를 조회하시오.
SELECT * FROM emp WHERE ENAME LIKE 'S%';

-- 5-21 사원 이름 두번째 글자가 L인 데이터를 조회하시오.
SELECT * FROM emp WHERE ENAME LIKE '_L%';

-- 5-22 사원 이름 중 AM 포함하는 데이터를 조회하시오.
SELECT * FROM emp WHERE ENAME LIKE '%AM%';

-- 5-23 사원 이름 중 AM 포함하지 않는 데이터를 조회하시오.
SELECT * FROM emp WHERE ENAME NOT LIKE '%AM%';

-- UNION 5-30
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20;

-- UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

--MINUS : 10번 부서 제외한 모든 직원
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

-- INTERSECT : 10번 부서 직원만
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP
INTERSECT 
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

-- 이름이 M으로 시작하거나 N으로 끝나는 직원의 사번, 이름, 입사일을 조회하시오.
SELECT EMPNO, ENAME, HIREDATE FROM EMP WHERE ENAME LIKE 'M%' OR ENAME LIKE '%N' ORDER BY ENAME;

-- 직무가 SALESMAN이 아닌 직원 중에서 급여가 1500 이상 3000 이하인 직원의 이름, 직무, 급여, 연봉을 조회하시오.
SELECT ENAME, SAL, JOB, SAL * 12 + NVL(COMM, 0) AS ANNUAL_SAL FROM EMP WHERE JOB != 'SALESMAN' AND SAL BETWEEN 1500 AND 3000;

-- 관리자가 있는 직원 중 급여가 2000 이상인 직원의 이름, 관리자번호, 급여를 조회하고 관리자번호, 사원 이름 순으로 정렬하시오.
SELECT ENAME, MGR, SAL FROM EMP WHERE MGR IS NOT NULL AND SAL >= 2000 ORDER BY MGR, ENAME;

-- 부서 번호가 10과 30의 직원 중 급여가 1500 이상인 직원을 UNION을 사용하여 조회하시오.
-- 사번, 이름, 급여, 부서번호를 출력하고 부서번호 오름차순, 급여 내림차순 기준으로 정렬하시오.
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE SAL >= 1500 AND DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE SAL >= 1500 AND DEPTNO = 30
ORDER BY DEPTNO, SAL DESC;